from pathlib import Path
import nbformat as n
ROOT=Path(__file__).resolve().parents[1]
def md(t):return n.v4.new_markdown_cell(t)
def code(t):return n.v4.new_code_cell(t)
def write(name,cells):n.write(n.v4.new_notebook(cells=cells,metadata={'kernelspec':{'name':'python3','display_name':'Python 3','language':'python'}}),ROOT/'notebooks'/name)
setup="""import os,sys,json
from pathlib import Path
os.environ['OPENBLAS_NUM_THREADS']='2'
os.environ['OMP_NUM_THREADS']='2'
ROOT=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'src/experiment.py').exists())
sys.path.insert(0,str(ROOT/'src'))
from IPython.display import display,Image,Code
"""
scratch=(ROOT/'src/scratch.py').read_text(encoding='utf-8')
frameworks=(ROOT/'src/frameworks.py').read_text(encoding='utf-8')
exp=(ROOT/'src/experiment.py').read_text(encoding='utf-8').split("if __name__=='__main__':")[0]
exp='\n'.join(line for line in exp.splitlines() if not line.startswith(('from scratch import','from frameworks import','ROOT=','matplotlib.use')))
descriptions={
'diabetes':'CDC BRFSS 2015: nhãn 0=no diabetes, 1=gộp prediabetes/diabetes. Gom nhóm predictor giống hệt trước chia tập để tránh leakage. Chỉ dùng benchmark 16.000/4.000/5.000 mẫu, không nhận là huấn luyện toàn bộ nguồn. Class weight tính từ train.',
'housing':'Giá nhà Việt Nam 2024: sáu biến số diện tích/mặt tiền/đường/số tầng/phòng; chưa dùng vị trí. Chia theo Address để tránh cùng địa chỉ ở nhiều tập. Điền median train, log1p, chuẩn hóa train; target log1p(Price), đổi lại tỷ VND khi đánh giá. Không xóa ngoại lệ bằng phân vị test.',
'mnist':'MNIST: 10.000 train, 2.000 validation lấy từ train chính thức, 2.000 test từ test chính thức. Resize 16×16 để scratch CNN train được trên CPU; không dùng pretrained. CNN valid3×3 → ReLU → average pool2 → flatten → logits10.',
'eurosat':'EuroSAT: nguồn 27.000 ảnh RGB, chọn phân tầng 10.000 ảnh, chia 6.400/1.600/2.000. Resize16, mean/std từng kênh chỉ train. Đây là benchmark nhỏ, không phải kết quả đầy đủ ảnh 64×64. Không spatial split nên chưa khẳng định khái quát sang địa lý mới.',
'stock':'AAPL: 30 phiên tám đặc trưng nhân quả → log-return phiên kế tiếp. Chia theo ngày nhãn, chuẩn hóa train-only. Mỗi dự đoán test nhận lịch sử thực đã quan sát, không dự báo đệ quy cả chuỗi. So với persistence Close_t=Close_{t-1}.',
'customer':'Online Retail II: gom 8 tuần × 6 tổng giao dịch → có đơn ở tuần kế tiếp. Chỉ khách có mua trong tám tuần trước, các mốc nhãn cách bốn tuần. CustomerID không làm predictor, nhưng khách có thể xuất hiện ở nhiều thời kỳ. Weighted softmax hai lớp, ngưỡng argmax (0,5), không gọi là churn.'}
for number,title,keys in [('02','ML cơ bản',['diabetes','housing']),('03','CNN',['mnist','eurosat']),('04','RNN',['stock','customer'])]:
    cells=[md(f'# Chương {int(number)} – {title}\nNguyễn Minh Vinh · B23DCCN934. Code tự triển khai và kết quả thật. Chạy tuần tự từng cell; các cell train sẽ huấn luyện lại. So sánh scratch / Keras / PyTorch cùng cấu trúc, initialization, split và minibatch.'),code(setup),md('## 1. Scratch: forward, loss, backward và SGD\nNumPy không dùng autograd. MLP áp dụng chain rule; CNN tính gradient kernel từ patch và phân phối gradient average pooling; RNN thực hiện BPTT từ bước cuối về đầu. Gradient clipping global norm=1 trước SGD.'),code(scratch),md('## 2. Hai framework cùng cấu trúc\nPyTorch dùng ParameterDict và phép toán tensor tự động đạo hàm, đặc biệt RNN chỉ có một bias để trùng với scratch và Keras. Keras dùng Dense/Conv2D/SimpleRNN. Head giữ thứ tự flatten NHWC cho cả ba.'),code(frameworks),md('## 3. Vòng train và metric\nCùng seed42, SGD không momentum, lr0,02 (MLP/RNN) hoặc0,04(CNN), batch128; epoch18 hoặc20. Chọn checkpoint validation loss nhỏ nhất. Chọn implementation bằng validation MacroF1 hoặc RMSE, rồi đọc test. Loss có class weights train, nhưng metric tính trên test tự nhiên.'),code(exp)]
    for key in keys:
        cells += [md(f'## 4. Dataset {key}\n'+descriptions[key]),code(f"import subprocess\nif not (ROOT/'data/{key}.npz').exists():\n    subprocess.run([sys.executable,str(ROOT/'tools/prepare.py'),'{key}'],check=True)\ndata=load('{key}')\ndisplay(pd.Series(data['meta']))\nprint('Input shape:',data['x'].shape)\ndisplay(pd.DataFrame(data['x'][data['train'][:3]].reshape(3,-1)[:,:8]))\nprint('Nhãn mẫu:',data['raw_y'][data['train'][:3]])"),md('### Tiền xử lý cụ thể\nMã chuẩn bị dữ liệu được trình bày dưới đây để đối chiếu fit scope và nguồn. Khi cần tái tạo cache, chạy tools/prepare.py với tên dataset. Chuỗi thời gian có thêm prepare_sequences.py.'),code("display(Code(filename=str(ROOT/'tools/prepare.py'),language='python'))" )]
        if key in ['stock','customer']:cells += [code("display(Code(filename=str(ROOT/'tools/prepare_sequences.py'),language='python'))")]
        for fw in ['scratch','keras','pytorch']:
            cells += [md(f'### Huấn luyện {fw}\nLưu history từng epoch, checkpoint tốt nhất, metric validation và dự đoán test. Không dùng trọng số hay số liệu từ bài mẫu.'),code(f"row=train('{key}','{fw}')\ndisplay(row)")]
        cells += [md('### So sánh và phân tích\nĐọc số liệu và hình do các lần train vừa tạo. Metric giữa các framework gần nhau là điều có thể xảy ra khi cùng khởi tạo và cùng SGD; không tự suy ra framework nào tốt hơn từ một seed.'),code(f"display(summarize('{key}').round(5))\nfor file in ['learning.png','evaluation.png','samples.png']:\n    path=ROOT/'results/{key}'/file\n    if path.exists():display(Image(filename=str(path)))\nprint('Baseline:',(ROOT/'results/{key}/baseline.json').read_text())\nprint('Chọn validation:',(ROOT/'results/{key}/selection.json').read_text())\ndisplay(pd.read_json(ROOT/'results/{key}/errors.json'))")]
    cells += [md('## 5. Tiểu kết\nMỗi dataset có ba implementation được train độc lập. Kết quả chỉ áp dụng cho cấu hình nhỏ và seed42, chưa có đánh giá nhiều seed. Báo cáo nêu baseline và failure cases; không chọn model bằng test. Kiểm tra gradient bằng tools/check_gradients.py và checkpoint bằng tools/verify.py.')]
    write(f'{number}_{title.split()[0]}_experiments.ipynb',cells)
write('01_history_and_data.ipynb',[md('# Chương 1 – Lịch sử AI và dữ liệu minh họa\nLịch sử chi tiết và tài liệu gốc nằm trong báo cáo. Notebook minh họa sự khác nhau giữa dữ liệu bảng, ảnh và chuỗi, không gán các mô hình hiện đại thành kết quả lịch sử.'),code(setup),code('import numpy as np,pandas as pd'),md('## Ba dataset đại diện\nCDC: bảng khảo sát; MNIST: ảnh chữ số; AAPL: chuỗi OHLCV. Mỗi nguồn có quy mô, mẫu nhãn, phân bố và giới hạn riêng. Cùng một metric không dùng để so khác bài toán.'),code("for key in ['diabetes','mnist','stock']:\n    meta=json.loads((ROOT/'results'/key/'summary.json').read_text(encoding='utf-8'))\n    display(pd.Series(meta))\n    d=np.load(ROOT/'data'/f'{key}.npz')\n    print('Một số target:',d['raw_y'][:5])\n    path=ROOT/'results'/key/'evaluation.png'\n    if path.exists():display(Image(filename=str(path)))"),md('## Kiểm tra gradient scratch\nFinite differences kiểm tra độc lập đạo hàm; sau đó đối chiếu autograd PyTorch/Keras trên cùng trọng số. Sai số nhỏ chỉ xác nhận phép toán, không bảo đảm mô hình dự đoán tốt.'),code("display(pd.read_json(ROOT/'results/gradient_checks.json'))")])
write('05_comparison_deploy.ipynb',[md('# Tổng hợp, đóng gói và triển khai\nĐọc kết quả đã huấn luyện; không chọn lại theo test.'),code(setup),code("import pandas as pd\nfor key in ['diabetes','housing','mnist','eurosat','stock','customer']:\n    print(key)\n    display(pd.read_csv(ROOT/'results'/key/'comparison.csv'))\n    print((ROOT/'results'/key/'selection.json').read_text())"),md('## Đóng gói web\nWeb dùng cùng NumPy forward với trọng số export từ ba implementation. Trọng số gốc Keras/PyTorch được lưu song song. Xem docs/DEPLOY.md; trạng thái live luôn ghi riêng.'),code("import runpy\nrunpy.run_path(str(ROOT/'tools/bundle.py'),run_name='__main__')"),md('## Giới hạn\nMột seed, benchmark ảnh giảm kích thước, chưa thực hiện grid search hoặc calibration. Không gọi đây là benchmark tốc độ phần cứng chung hoặc công cụ chẩn đoán/định giá thực tế.')])
print('Wrote 5 notebooks')
